{{- if .Values.datasync.enabled }}
apiVersion: v1
kind: Service
metadata:
  
  labels:
    io.kompose.service: {{  .Values.imageRepository.datasync.fullName   }}
  name: {{  .Values.imageRepository.datasync.fullName   }}
spec:
  ports:
  - name: "9980"
    port: 9980
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: {{  .Values.imageRepository.datasync.fullName   }}
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}