{{- if .Values.datasync.enabled }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{  .Values.imageRepository.datasync.fullName   }}
  namespace: {{ .Release.Namespace   }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
      {{ $key }}: {{ $value }}
    {{- end }}
  generation: 1
  labels:
    release: {{ .Release.Name }}
    io.kompose.service: {{  .Values.imageRepository.datasync.fullName   }}
spec:
  replicas: 1
  selector:
    matchLabels: {{  .Values.imageRepository.datasync.fullName   }}
      io.kompose.service: {{  .Values.imageRepository.datasync.fullName   }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: {{  .Values.imageRepository.datasync.fullName   }}
    spec:
      containers:
      - name: {{  .Values.imageRepository.datasync.fullName   }}
        image: {{ .Values.imageRepository.datasync.image }}:{{ .Values.imageRepository.datasync.imageTag }}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - sudo chown -R mgeweb:mgeweb /home/mgeweb/pacotes-datasync/ && java -jar /home/mgeweb/DDM/docker-datasync-manager.jar  && sleep 5 && sudo chown -R mgeweb:mgeweb /home/mgeweb/DataSync/ && /home/mgeweb/DDM/scripts/./run-datasync.sh && /home/mgeweb/DataSync/./datasync-service start && sleep 15 && tail -f /home/mgeweb/DataSync/log/server.log
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
        volumeMounts:
        - mountPath: /home/mgeweb/DataSync/conf
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/conf
        - mountPath: /home/mgeweb/DataSync/email
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/email
        - mountPath: /home/mgeweb/DataSync/exported
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/exported
        - mountPath: /home/mgeweb/DataSync/filetransfer_home
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/filetransfer_home
        - mountPath: /home/mgeweb/DataSync/log
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/log
        - mountPath: /home/mgeweb/DataSync/processed
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/processed
        - mountPath: /home/mgeweb/DataSync/sync
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/sync
        - mountPath: /home/mgeweb/DataSync/tracking
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/tracking
        - mountPath: /home/mgeweb/DataSync/work
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/work
        - mountPath: /home/mgeweb/pacotes-datasync/
          name: {{ .Release.Namespace   }}-volume
          subPath: highlander/datasync/pacotes/datasync
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: {{ .Release.Namespace   }}-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace   }}-volume
status: {}
{{- end }}
