{{- if .Values.esocial.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.imageRepository.esocial.fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    io.kompose.service: {{  .Values.imageRepository.esocial.fullName }}
spec:
  ports:
  - name: "9970"
    port: 9970
    protocol: TCP
    targetPort: 8778
  selector:
    io.kompose.service: {{  .Values.imageRepository.esocial.fullName }}
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}