apiVersion: v1
kind: Service
metadata:
  name: {{ template "jiva-w.server.fullname" . }}
spec:
  ports:
  - name: "9990"
    port: 9990
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
status:
  loadBalancer: {}
