apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: jiva-w-service
  name: jiva-w-service
spec:
  ports:
  - name: "9990"
    port: 9990
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: jiva-w-service
  type: ClusterIP
status:
  loadBalancer: {}
