apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jiva-w
  name: jiva-w
spec:
  ports:
  - name: "9990"
    port: 9990
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: jiva-w
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
