apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: jiva-w
  name: jiva-w
spec:
  ports:
  - name: "8080"
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: jiva-w
status:
  loadBalancer: {}
