apiVersion: apps/v1beta2
kind: Deployment
metadata:
  generation: 1
  labels:
    io.kompose.service: sanesocial
  name: sanesocial
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: sanesocial
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2019-03-19T15:23:43Z"
      creationTimestamp: null
      labels:
        io.kompose.service: sanesocial
    spec:
      containers:
      - args:
        - java -jar /home/mgeweb/DSEM/docker-sanesocial-manager.jar && sleep 5 &&
          /home/mgeweb/DSEM/scripts/./run-sanesocial.sh && sleep 15 && /home/mgeweb/sanesocial/./sanesocial-service
          start && sleep 15 && nohup /home/mgeweb/DSEM/scripts/./sentry  2>&1 </dev/null
          & sleep 15 && echo 'y' && sleep 15 && tail -f /home/mgeweb/sanesocial/log/server.log
        command:
        - /bin/sh
        - -c
        env:
        - name: APP
          value: SanEsocial
        - name: CLIENTE
          value: jiva-w
        - name: PATH_LOG
          value: /home/mgeweb/sanesocial/log/server.log
        image: highlanderdantas/esocial:v1.4
        imagePullPolicy: Always
        name: sanesocial
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /home/mgeweb/sanesocial/conf
          name: sanesocial-claim0
          subPath: sanesocial/conf
        - mountPath: /home/mgeweb/sanesocial/certificados
          name: sanesocial-claim0
          subPath: sanesocial/certificados
        - mountPath: /home/mgeweb/sanesocial/log
          name: sanesocial-claim0
          subPath: sanesocial/log
        - mountPath: /home/mgeweb/sanesocial/properties
          name: sanesocial-claim0
          subPath: sanesocial/properties
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: sanesocial-claim0
        persistentVolumeClaim:
          claimName: sanesocial-claim0
status: {}
