apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sas
  generation: 1
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value }}
      {{- end }}
      labels:
        app: jiva-w
        release: "{{ .Release.Name }}"
      selector:
    matchLabels:
      io.kompose.service: sas
    spec:
      containers:
      - name: sas
        image: {{  .Values.imageRepository.sas.image }}:{{  .Values.imageRepository.sas.imageTag }}
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - sudo chown -R mgeweb:mgeweb  /home/mgeweb/pacotes-sas/ /tmp/ && java -jar /opt/DSM/docker-sas-manager.jar /SAS && sleep 5 && tar -xzf /tmp/SAS.tar.gz -C /tmp/ &&  sudo chown -R mgeweb:mgeweb /tmp/ /opt/SAS/* && sleep 5  && /opt/DSM/scripts/./run-sas.sh && sleep 2 && tail -f /opt/SAS/log/server*.log
        env: 
        - name: HASDELPHI
          value: {{ .Values.sasdelphi.enabled }}
        - name: IP_BD_JIVAW
          value: {{ .Values.banco.ip }}
        - name: PORTA_BD_JIVAW
          value: {{ .Values.banco.porta }}
        - name: SENHA_BD_JIVAW
          value: {{ .Values.banco.senha }}
        - name: SID_BD_JIVAW
          value: {{ .Values.banco.sid }}
        - name: TIPO_BD
          value: {{ .Values.banco.tipo }}
        - name: USUARIO_BD_JIVAW
          value: {{ .Values.banco.usuario }}
        livenessProbe:
          failureThreshold: 2
          initialDelaySeconds: 6
          periodSeconds: 6
          successThreshold: 1
          tcpSocket:
            port: 10050
          timeoutSeconds: 6
        readinessProbe:
          failureThreshold: 2
          initialDelaySeconds: 6
          periodSeconds: 6
          successThreshold: 1
          tcpSocket:
            port: 10050
          timeoutSeconds: 6
        volumeMounts:
        - mountPath: /home/mgeweb/pacotes-sas/
          name: {{ .Values.imageRepository.volume }}
          subPath: pacotes/sas
        - mountPath: /opt/SAS/licenca
          name: {{ .Values.imageRepository.volume }}
          subPath: highlander/SAS/
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: {{ .Values.imageRepository.volume }}
        persistentVolumeClaim:
          claimName: {{ .Values.imageRepository.volume }}
status: {}
