apiVersion: apps/v1beta2
kind: Deployment
metadata:
  generation: 1
  labels:
    io.kompose.service: sas
  name: sas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sas
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      labels:
        io.kompose.service: sas
    spec:
      containers:
      - name: sas
        image: highlanderdantas/sas:v1.4
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - sudo chown -R mgeweb:mgeweb  /home/mgeweb/pacotes-sas/ /tmp/ && java -jar /opt/DSM/docker-sas-manager.jar /SAS && sleep 5 && tar -xzf /tmp/SAS.tar.gz -C /tmp/ &&  sudo chown -R mgeweb:mgeweb /tmp/ /opt/SAS/* && sleep 5  && /opt/DSM/scripts/./run-sas.sh && sleep 2 && tail -f /opt/SAS/log/server*.log
        env: 
        - name: HASDELPHI
          value: 'false'
        - name: IP_BD_JIVAW
          value: '192.168.0.137'
        - name: PORTA_BD_JIVAW
          value: '1521'
        - name: SENHA_BD_JIVAW
          value: tecsis
        - name: SID_BD_JIVAW
          value: ORCL
        - name: TIPO_BD
          value: ORACLE
        - name: USUARIO_BD_JIVAW
          value: PAULO2
        livenessProbe:
          failureThreshold: 2
          initialDelaySeconds: 6
          periodSeconds: 6
          successThreshold: 1
          tcpSocket:
            port: 10050
          timeoutSeconds: 6
        readinessProbe:
          failureThreshold: 2
          initialDelaySeconds: 6
          periodSeconds: 6
          successThreshold: 1
          tcpSocket:
            port: 10050
          timeoutSeconds: 6
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities: {}
          privileged: true
          procMount: Default
        volumeMounts:
        - mountPath: /home/mgeweb/pacotes-sas/
          name: sanesocial-claim0
          subPath: pacotes/sas
        - mountPath: /opt/SAS/licenca
          name: sanesocial-claim0
          subPath: highlander/SAS/
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: sanesocial-claim0
        persistentVolumeClaim:
          claimName: sanesocial-claim0
status: {}
