name: OracldbExporter
description: |
  Container OracldbExporter com para monitoramento pelo Prometheus e Grafana
version: 1.0
category: Collaboration
maintainer: Highlander Dantas <highlander.dantas@sankhya.com.br>
