# Imagens Hub e Versões
imageRepository:
  jivaw:
    fullName: "jiva-w"
    image: "highlanderdantas/snk-jiva-w"
    imageTag: "v1.4"
    volume: "sanesocial-claim0"
  sas:
    fullName: "sas" 
    image: "highlanderdantas/sas"
    imageTag: "v1.4"
    volume: "sanesocial-claim0"
  esocial:
    fullName: "esocial"
    image: "highlanderdantas/esocial"
    imageTag: "v1.4"
    volume: "sanesocial-claim0"
  datasync: 
    fullName: "datasync"
    image: "highlanderdantas/datasync"
    imageTag: v1.4
    volume: "sanesocial-claim0"

annotations: {}

## Pacote para Instalação
pacote:
  versao: "jiva-w_3.29b91.pkg"
  versionNew: ""

## Dados do Banco de Dados
banco:
  tipo: "ORACLE"
  ip: ""
  porta: "1521"
  sid: "ORCL"
  usuario: "System"
  senha: "tecsis"

## Memoria Jivaw
memoria:
  jivaw:
    jboss: "-Xms512m -Xmx1304m"
    maximo: "1536"
    media: "1024"

## Possui SAs
sasdelphi:
  enabled: false

## Possui Datasync
datasync:
  enabled: false

## Possui Esocial
esocial:
  enabled: false

## Configurações de url de acesso
loadBalancer:
  jivaw:
    enabled: false
    hostname: ""
  datasync:
    enabled: false
    hostname: ""
  sanesocial:
    enabled: false
    hostname: ""

