name: OracleDB Exporter
description: |
  Container OracleDB Exporter com para monitoramento pelo Prometheus e Grafana
version: 1.1
category: Collaboration
maintainer: Highlander Dantas <highlander.dantas@sankhya.com.br>
