apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: datasync
  name: datasync
spec:
  ports:
  - name: "9980"
    port: 9980
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: datasync
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
