apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume-claim
  annotations:
    {{- range $key, $value := .Values.annotations }}
      {{ $key }}: {{ $value }}
    {{- end }}
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    io.kompose.service: nfs-volume-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "{{ .Values.storageClass.defaultClass }}"
  resources:
    requests:
      storage: 20Gi