teatrou:
  image: highlanderdantas/teatrou:2
  restart: always
  environment: 
    - ACESS_KEY=${acess_key}
    - SECRET_KEY=${secret_key}
    - USERNAME=${username}
    - SENHA_APP=${senha_app}
    - EMAIL_PAGSEGURO=${email_pagseguro}
    - TOKEN_PAGSEGURO=${token_pagseguro}
    - URL_BANCO=${url_banco}
    - USER_BANCO=${user_banco}
    - PASSWORD_BANCO=${password_banco}
  ports:
    - "8080"
  health_check:
    port: 8080
    request_line: GET / HTTP/1.0
    interval: 90000
    initializing_timeout: 300000
    reinitializing_timeout: 300000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 1
    response_timeout: 60000
