{{- if .Values.esocial.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: esocial
  labels:
    io.kompose.service: esocial
spec:
  selector:
    io.kompose.service: esocial
status:
  loadBalancer: {}
{{- end }}